var action = argument0;

if(action == "load"){
	oPlayer.hp = ds_map_find_value(oController.player_stats, "hp");
	oPlayer.energy_tanks = ds_map_find_value(oController.player_stats, "energy_tanks");
	oPlayer.max_hp = ds_map_find_value(oController.player_stats, "max_hp");
	oPlayer.missiles = ds_map_find_value(oController.player_stats, "missiles");
	oPlayer.max_jumps = ds_map_find_value(oController.player_stats, "max_jumps");
	oPlayer.max_dashes = ds_map_find_value(oController.player_stats, "max_dashes");
	oPlayer.has_missiles = ds_map_find_value(oController.player_stats, "has_missiles");
	oPlayer.has_spread = ds_map_find_value(oController.player_stats, "has_spread");
	oPlayer.has_bombs = ds_map_find_value(oController.player_stats, "has_bombs");
	oPlayer.has_wave = ds_map_find_value(oController.player_stats, "has_wave");
	oPlayer.has_screw_attack = ds_map_find_value(oController.player_stats, "has_screw_attack");
	oPlayer.has_orb_slash = ds_map_find_value(oController.player_stats, "has_orb_slash");
	oPlayer.has_mod_system = ds_map_find_value(oController.player_stats, "has_mod_system");
	oPlayer.can_hook = ds_map_find_value(oController.player_stats, "can_hook");
	oPlayer.can_triple_jump = ds_map_find_value(oController.player_stats, "can_triple_jump");
	oPlayer.can_double_dash = ds_map_find_value(oController.player_stats, "can_double_dash");
	oPlayer.can_triple_dash = ds_map_find_value(oController.player_stats, "can_triple_dash");
	oPlayer.has_regen = ds_map_find_value(oController.player_stats, "has_regen");
	oPlayer.has_sharp_dash = ds_map_find_value(oController.player_stats, "has_sharp_dash");
	oPlayer.has_shield = ds_map_find_value(oController.player_stats, "has_shield");
	oPlayer.has_turbo = ds_map_find_value(oController.player_stats, "has_turbo");
	oPlayer.has_long_slash = ds_map_find_value(oController.player_stats, "has_long_slash");
	oPlayer.has_strong_slash = ds_map_find_value(oController.player_stats, "has_strong_slash");
	oPlayer.has_sticky_hang = ds_map_find_value(oController.player_stats, "has_sticky_hang");
	oPlayer.has_slow_fall = ds_map_find_value(oController.player_stats, "has_slow_fall");
	oPlayer.has_small_avatar = ds_map_find_value(oController.player_stats, "has_small_avatar");
	oPlayer.has_super_bombs = ds_map_find_value(oController.player_stats, "has_super_bombs");
	oPlayer.has_cluster_missiles = ds_map_find_value(oController.player_stats, "has_cluster_missiles");
} else if (action == "set"){	
	ds_map_set(oController.player_stats,"hp",oPlayer.hp);
	ds_map_set(oController.player_stats,"energy_tanks",oPlayer.energy_tanks);
	ds_map_set(oController.player_stats,"max_hp",oPlayer.max_hp);
	ds_map_set(oController.player_stats,"missiles",oPlayer.missiles);
	ds_map_set(oController.player_stats,"max_jumps",oPlayer.max_jumps);
	ds_map_set(oController.player_stats,"max_dashes",oPlayer.max_dashes);
	ds_map_set(oController.player_stats,"has_missiles",oPlayer.has_missiles);
	ds_map_set(oController.player_stats,"has_spread",oPlayer.has_spread);
	ds_map_set(oController.player_stats,"has_bombs",oPlayer.has_bombs);
	ds_map_set(oController.player_stats,"has_wave",oPlayer.has_wave);
	ds_map_set(oController.player_stats,"has_screw_attack",oPlayer.has_screw_attack);
	ds_map_set(oController.player_stats,"has_orb_slash",oPlayer.has_orb_slash);
	ds_map_set(oController.player_stats,"has_mod_system",oPlayer.has_mod_system);
	ds_map_set(oController.player_stats,"can_hook",oPlayer.can_hook);
	ds_map_set(oController.player_stats,"can_triple_jump",oPlayer.can_triple_jump);
	ds_map_set(oController.player_stats,"can_double_dash",oPlayer.can_double_dash);
	ds_map_set(oController.player_stats,"can_triple_dash",oPlayer.can_triple_dash);
	ds_map_set(oController.player_stats,"has_regen",oPlayer.has_regen);
	ds_map_set(oController.player_stats,"has_sharp_dash",oPlayer.has_sharp_dash);
	ds_map_set(oController.player_stats,"has_shield",oPlayer.has_shield);
	ds_map_set(oController.player_stats,"has_turbo",oPlayer.has_turbo);
	ds_map_set(oController.player_stats,"has_strong_slash",oPlayer.has_strong_slash);
	ds_map_set(oController.player_stats,"has_long_slash",oPlayer.has_long_slash);
	ds_map_set(oController.player_stats,"has_sticky_hang",oPlayer.has_sticky_hang);
	ds_map_set(oController.player_stats,"has_slow_fall",oPlayer.has_slow_fall);
	ds_map_set(oController.player_stats,"has_small_avatar",oPlayer.has_small_avatar);
	ds_map_set(oController.player_stats,"has_super_bombs",oPlayer.has_super_bombs);
	ds_map_set(oController.player_stats,"has_cluster_missiles",oPlayer.has_cluster_missiles);
} else if (action == "create"){
	ds_map_add(oController.player_stats,"hp",oPlayer.hp);
	ds_map_add(oController.player_stats,"max_hp",oPlayer.max_hp);
	ds_map_add(oController.player_stats,"energy_tanks",oPlayer.energy_tanks);
	ds_map_add(oController.player_stats,"missiles",oPlayer.missiles);
	ds_map_add(oController.player_stats,"max_jumps",oPlayer.max_jumps);
	ds_map_add(oController.player_stats,"max_dashes",oPlayer.max_dashes);
	ds_map_add(oController.player_stats,"has_missiles",oPlayer.has_missiles);
	ds_map_add(oController.player_stats,"has_spread",oPlayer.has_spread);
	ds_map_add(oController.player_stats,"has_bombs",oPlayer.has_bombs);
	ds_map_add(oController.player_stats,"has_wave",oPlayer.has_wave);
	ds_map_add(oController.player_stats,"has_screw_attack",oPlayer.has_screw_attack);
	ds_map_add(oController.player_stats,"has_orb_slash",oPlayer.has_orb_slash);
	ds_map_add(oController.player_stats,"has_mod_system",oPlayer.has_mod_system);
	ds_map_add(oController.player_stats,"can_hook",oPlayer.can_hook);
	ds_map_add(oController.player_stats,"can_triple_jump",oPlayer.can_triple_jump);
	ds_map_add(oController.player_stats,"can_double_dash",oPlayer.can_double_dash);
	ds_map_add(oController.player_stats,"can_triple_dash",oPlayer.can_triple_dash);
	ds_map_add(oController.player_stats,"has_regen",oPlayer.has_regen);
	ds_map_add(oController.player_stats,"has_sharp_dash",oPlayer.has_sharp_dash);
	ds_map_add(oController.player_stats,"has_shield",oPlayer.has_shield);
	ds_map_add(oController.player_stats,"has_turbo",oPlayer.has_turbo);
	ds_map_add(oController.player_stats,"has_strong_slash",oPlayer.has_strong_slash);
	ds_map_add(oController.player_stats,"has_long_slash",oPlayer.has_long_slash);
	ds_map_add(oController.player_stats,"has_sticky_hang",oPlayer.has_sticky_hang);
	ds_map_add(oController.player_stats,"has_slow_fall",oPlayer.has_slow_fall);
	ds_map_add(oController.player_stats,"has_small_avatar",oPlayer.has_small_avatar);
	ds_map_add(oController.player_stats,"has_super_bombs",oPlayer.has_super_bombs);
	ds_map_add(oController.player_stats,"has_cluster_missiles",oPlayer.has_cluster_missiles);
}