// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // obControl
global.__objectDepths[1] = -100; // obPlayer
global.__objectDepths[2] = -100; // obEnemy
global.__objectDepths[3] = -100; // obAlly
global.__objectDepths[4] = 0; // obPlayerParent
global.__objectDepths[5] = 0; // obAds
global.__objectDepths[6] = -200; // obEffect_00
global.__objectDepths[7] = -120; // obReturn
global.__objectDepths[8] = -9000; // obDamage
global.__objectDepths[9] = 0; // obSmoke
global.__objectDepths[10] = -150; // obHeart
global.__objectDepths[11] = -120; // obAnimal
global.__objectDepths[12] = -180; // obDamageNumber
global.__objectDepths[13] = -30000; // obBattle
global.__objectDepths[14] = -30000; // obVictory
global.__objectDepths[15] = -250; // obFlareGame
global.__objectDepths[16] = -200; // obMove
global.__objectDepths[17] = -200; // obCard
global.__objectDepths[18] = -200; // obJump
global.__objectDepths[19] = 0; // obButtons
global.__objectDepths[20] = -12; // obStar
global.__objectDepths[21] = -11; // obMission
global.__objectDepths[22] = -11; // obOverview
global.__objectDepths[23] = -9999; // obQuest
global.__objectDepths[24] = 0; // obGameMenu
global.__objectDepths[25] = 0; // obMenuButtons
global.__objectDepths[26] = -8; // obGroundParent
global.__objectDepths[27] = 0; // obGround
global.__objectDepths[28] = 0; // obEnviromentParent
global.__objectDepths[29] = -800; // obSun
global.__objectDepths[30] = -70; // obPart
global.__objectDepths[31] = -500; // obBackSpells
global.__objectDepths[32] = -2000; // obMessage
global.__objectDepths[33] = -10; // obBlack
global.__objectDepths[34] = -99999; // obBlack2
global.__objectDepths[35] = -1000000; // obBlack3
global.__objectDepths[36] = -1555; // obArrow
global.__objectDepths[37] = -10001; // obDrawSpellAssign
global.__objectDepths[38] = -2500; // obPortal
global.__objectDepths[39] = -13; // obItems
global.__objectDepths[40] = -13; // obOpenPortal
global.__objectDepths[41] = -13; // obBuyChamp
global.__objectDepths[42] = 0; // obChatDrag
global.__objectDepths[43] = -13; // obHeroLab
global.__objectDepths[44] = -2400; // obParts
global.__objectDepths[45] = -500; // obExit
global.__objectDepths[46] = -500; // obCharacter
global.__objectDepths[47] = 0; // obBlackMenu
global.__objectDepths[48] = 0; // obShopParent
global.__objectDepths[49] = 50; // obBack00
global.__objectDepths[50] = -1; // obAudio
global.__objectDepths[51] = -12; // obChampionNext
global.__objectDepths[52] = -1; // obChoose
global.__objectDepths[53] = -1; // obArcade
global.__objectDepths[54] = -5555555; // obClose
global.__objectDepths[55] = -1; // obInfo
global.__objectDepths[56] = -12; // obMissionNext
global.__objectDepths[57] = -1750; // obNext
global.__objectDepths[58] = -7; // obPlay
global.__objectDepths[59] = -1; // obShop
global.__objectDepths[60] = -12; // obShopNext
global.__objectDepths[61] = -7; // obStart
global.__objectDepths[62] = -7; // obStats
global.__objectDepths[63] = -1; // obTrophy
global.__objectDepths[64] = -12; // obTrophyNext


global.__objectNames[0] = "obControl";
global.__objectNames[1] = "obPlayer";
global.__objectNames[2] = "obEnemy";
global.__objectNames[3] = "obAlly";
global.__objectNames[4] = "obPlayerParent";
global.__objectNames[5] = "obAds";
global.__objectNames[6] = "obEffect_00";
global.__objectNames[7] = "obReturn";
global.__objectNames[8] = "obDamage";
global.__objectNames[9] = "obSmoke";
global.__objectNames[10] = "obHeart";
global.__objectNames[11] = "obAnimal";
global.__objectNames[12] = "obDamageNumber";
global.__objectNames[13] = "obBattle";
global.__objectNames[14] = "obVictory";
global.__objectNames[15] = "obFlareGame";
global.__objectNames[16] = "obMove";
global.__objectNames[17] = "obCard";
global.__objectNames[18] = "obJump";
global.__objectNames[19] = "obButtons";
global.__objectNames[20] = "obStar";
global.__objectNames[21] = "obMission";
global.__objectNames[22] = "obOverview";
global.__objectNames[23] = "obQuest";
global.__objectNames[24] = "obGameMenu";
global.__objectNames[25] = "obMenuButtons";
global.__objectNames[26] = "obGroundParent";
global.__objectNames[27] = "obGround";
global.__objectNames[28] = "obEnviromentParent";
global.__objectNames[29] = "obSun";
global.__objectNames[30] = "obPart";
global.__objectNames[31] = "obBackSpells";
global.__objectNames[32] = "obMessage";
global.__objectNames[33] = "obBlack";
global.__objectNames[34] = "obBlack2";
global.__objectNames[35] = "obBlack3";
global.__objectNames[36] = "obArrow";
global.__objectNames[37] = "obDrawSpellAssign";
global.__objectNames[38] = "obPortal";
global.__objectNames[39] = "obItems";
global.__objectNames[40] = "obOpenPortal";
global.__objectNames[41] = "obBuyChamp";
global.__objectNames[42] = "obChatDrag";
global.__objectNames[43] = "obHeroLab";
global.__objectNames[44] = "obParts";
global.__objectNames[45] = "obExit";
global.__objectNames[46] = "obCharacter";
global.__objectNames[47] = "obBlackMenu";
global.__objectNames[48] = "obShopParent";
global.__objectNames[49] = "obBack00";
global.__objectNames[50] = "obAudio";
global.__objectNames[51] = "obChampionNext";
global.__objectNames[52] = "obChoose";
global.__objectNames[53] = "obArcade";
global.__objectNames[54] = "obClose";
global.__objectNames[55] = "obInfo";
global.__objectNames[56] = "obMissionNext";
global.__objectNames[57] = "obNext";
global.__objectNames[58] = "obPlay";
global.__objectNames[59] = "obShop";
global.__objectNames[60] = "obShopNext";
global.__objectNames[61] = "obStart";
global.__objectNames[62] = "obStats";
global.__objectNames[63] = "obTrophy";
global.__objectNames[64] = "obTrophyNext";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for